name: 🐞 Bug Report
description: Found a bug or issue on the site? Help us fix it by reporting here.
title: "[Bug] <short-description>"
labels: ["bug", "needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report  
        Thank you for taking the time to help improve this project! Please fill out the details below so we can address the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: Clearly and concisely describe what the bug is.
      placeholder: Something doesn't work the way it should...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior (if applicable).
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See the error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: It should've redirected to the contact page...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: Add screenshots or screen recordings to help explain the problem.
    validations:
      required: false

  - type: input
    id: device-desktop
    attributes:
      label: Desktop Environment (Optional)
      description: Provide browser and OS details.
      placeholder: Windows 11, Chrome v125
    validations:
      required: false

  - type: input
    id: device-mobile
    attributes:
      label: Mobile Environment (Optional)
      description: Device + Browser + OS
      placeholder: Pixel 6, Android 13, Chrome
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or links related to the issue.
    validations:
      required: false
