name: 🐛 Bug Report
description: File a bug to help us improve.
title: "[BUG] - "
labels: [bug]
assignees:
  - AyushHardeniya
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Let’s fix it together.
        
  - type: input
    id: description
    attributes:
      label: 📄 Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g. The homepage crashes when I surf Navbar or else...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧭 Steps to Reproduce
      description: What steps should we follow to recreate the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment Details
      description: OS, browser, device, GitHub version (if applicable)
    validations:
      required: false
