blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Discuss
    url: https://github.com/AyushHardeniya/ayushhardeniya.github.io/discussions
    about: Use GitHub Discussions for asking questions or general conversation.
